development:
  adapter: postgresql
  database: epicswap_dev
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: epicswap_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: epicswap
  pool: 5
  timeout: 5000
